# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 82a1dc5e4e0cb8861e296dc3d0dd63c8e381617753edb8225104caab2f08269330b3a24a5b098479ad6aae2c8ca7f5759ed68174b3d0b0d685406777e7b07589

test:
  secret_key_base: e570d8d27af3877609c9b0146a2d496c5550f2d4e8fabe6dc3176568a135fe590cc5a6fdc1856d108171f11606c2ad5bef5cc3c468508edb607df9ee6227d7ad

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
